name: S3 NWB Test
on:
  pull_request:
    branches: [master]
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build-and-test:
    name: Testing using ${{ matrix.os }} with ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: git fetch --prune --unshallow --tags
      - name: Install pytest
        run: |
          pip install pytest
          pip install pytest-cov
      - name: Install package
        run: |
          pip install -e .
          pip install pynwb
      - name: Install fsspec, aiohttp and requests
        run: pip install fsspec aiohttp requests
      - name: run tests
        run: pytest spikeinterface/extractors/tests/test_nwb_s3_extractor.py

# Note that in a previuos version conda was required to install h5py